name: Secret scan (TruffleHog)

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '17 2 * * *'  # daily at 02:17 UTC

# allow the Action to comment/annotate on PRs when it finds secrets
permissions:
  contents: read
  pull-requests: write
  issues: write
  id-token: write

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # scan needs history

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@v3.90.3
        # We keep the step alive to collect clean status and fail intentionally below
        continue-on-error: true
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified --fail-verified

      # Make the whole job fail if verified secrets were found
      - name: Fail if secrets found
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
