name: Secret scan (TruffleHog)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # NEW: find the root commit and expose it as an output
      - name: Find root commit
        id: root
        run: |
          ROOT=$(git rev-list --max-parents=0 HEAD | tail -n1)
          echo "root=$ROOT" >> "$GITHUB_OUTPUT"

      # OPTIONAL: sanity check so you can see it in the logs
      - name: Show root commit
        run: echo "Root is ${{ steps.root.outputs.root }}"
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
      - name: scan-push
        uses: trufflesecurity/trufflehog@main
        with:
          # base: "34f3c4ee626fbcbdc17356a431dbdb2c7997f7c4"
          path: ./
          base: ${{ steps.root.outputs.root }}
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown
# on:
#   pull_request:
#   push:
#     branches: [main]
#   schedule:
#     - cron: '17 2 * * *'  # daily at 02:17 UTC

# # allow the Action to comment/annotate on PRs when it finds secrets
# permissions:
#   contents: read
#   pull-requests: write
#   issues: write
#   id-token: write

# jobs:
#   trufflehog:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout full history
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0  # scan needs history

#       - name: TruffleHog OSS
#         id: trufflehog
#         uses: trufflesecurity/trufflehog@v3.90.3
#         # We keep the step alive to collect clean status and fail intentionally below
#         continue-on-error: true
#         with:
#           path: ./
#           base: ${{ github.event.repository.default_branch }}
#           head: HEAD
#           extra_args: --only-verified --fail-verified

#       # Make the whole job fail if verified secrets were found
#       - name: Fail if secrets found
#         if: steps.trufflehog.outcome == 'failure'
#         run: exit 1
